// Complete these tests...
// 1. check if My Todo Application text is there on component
// 2.. check if Add Item is there...
// 3. check if user clicks on Add Item button and enters' "grocery " .. grocery should be there in the document...
// 4.If user enters "exercise"  then read exercise and when use clicks on the exercise then it should change the style of that exercise as strike through.. toHaveStyle()..likewise make tests.. for the styling of the todo item
// 5. if user deletes an item.... that item is not in the document any more...
